### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [blackle/mastodon-data-viewer.py#7]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by blackle** [comment]
Thanks! I licensed it with CC0, as is usual for me (with the permission of the other contributors)

**Comment by TechnologyClassroom** [comment]
Just so you know, CC0 is not recommended of code. Fedora has recently banned CC0 code because it explicitly allows patenting. https://lwn.net/Articles/902410/
